# Copyright 2022 Manna Harbour
# https://github.com/manna-harbour/miryoku

name: 'Build corne display'
on: workflow_dispatch
jobs:
  build:
    uses: ./.github/workflows/main.yml
    secrets: inherit
    with:
      alphas: '["qwerty"]'
      nav: '["vi"]'
      board: '["nice_nano"]'
      shield: '["corne_left","corne_right","settings_reset"]'
      kconfig: '["CONFIG_ZMK_DISPLAY=y\nCONFIG_ZMK_IDLE_TIMEOUT=30000\nCONFIG_ZMK_SLEEP=y\nCONFIG_ZMK_IDLE_SLEEP_TIMEOUT=3600000\nCONFIG_BT_CTLR_TX_PWR_PLUS_8=y\nCONFIG_ZMK_KEYBOARD_NAME=\"crkbd\""]'
